//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroMonitorInternatinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesHistory
    {
        public int id { get; set; }
        public string Year { get; set; }
        public Nullable<int> VehiclesSold { get; set; }
        public Nullable<int> CarsId { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
